name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
        
  NonProdStaging:
    name: Deploy to NonProd Jump 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: JumpServer-NP
      url: 'http://www.google.com'
    steps:
      - name: Execute shell script
        run: src/main/java/com/example/teamconnect/myscript.sh
    
  DeployDev:
    name: Deploy to Dev 
    #if: github.event.ref == 'refs/heads/main'
    needs: [NonProdStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Development-CBT
      url: 'http://www.google.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployStaging:
    name: Deploy to Staging 
    #if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: JumpServer-Prod
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production-CBT
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
