name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
#To build the war in Jump box
  JumpBox:
    if: github.event.ref == 'refs/heads/main'
    runs-on: [self-hosted, linux]
    environment: 
      name: JumpServer-NP
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: SonarQube Scan
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build with Maven
        run: mvn clean install
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATEKEY }}
      - name: Copy war file
        #run: scp -i /root/.ssh/id_rsa target/*.war vvdn@192.168.126.63:/home/vvdn/logs
        run:  |
          echo "Vickey$123" | sudo -S scp target/*.war vvdn@192.168.126.63:/home/vvdn/logs
    
  DeployDev:
  #To deploy the war in development server
    name: Deploy to Dev 
    #if: github.event.ref == 'refs/heads/main'
    needs: [JumpBox]
    runs-on: ubuntu-latest
    environment: 
      name: Development-CBT
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute shell script
        run: sh myscript.sh
      
    
  DeployStaging:
  #To copy the war from development server to prod Jump box
    name: Deploy to Staging 
    #if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: JumpServer-Prod
      url: 'http://test.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
  #To deploy the war in Production server
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production-CBT
      url: 'http://www.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: echo I am deploying
